import type { Prediction } from "@/types";

export const MOCK_PREDICTIONS: Prediction[] = [
  {
    id: "1",
    sport: "nfl",
    league: "NFL",
    homeTeam: "Kansas City Chiefs",
    awayTeam: "Buffalo Bills",
    matchDate: new Date().toISOString(),
    prediction: "home_win",
    confidence: 78,
    riskLevel: "medium",
    volatilityScore: 6.2,
    isTrapGame: false,
    avoidMatch: false,
    avoidReason: null,
    reasoning:
      "Chiefs at home with Mahomes fully healthy. Bills secondary showing weakness past 3 weeks. Home field advantage amplified by crowd noise in playoff-like atmosphere.",
    keyFactors: ["Home advantage", "Mahomes health", "Bills secondary weakness"],
    weatherImpact: null,
    sharpMoneySignal: "Heavy sharp action on Chiefs -3.5",
    aiProbability: 78,
    bookmakerProbability: 62,
    valueDetected: true,
    tierRequired: "free",
  },
  {
    id: "2",
    sport: "nba",
    league: "NBA",
    homeTeam: "Boston Celtics",
    awayTeam: "Miami Heat",
    matchDate: new Date().toISOString(),
    prediction: "over",
    confidence: 65,
    riskLevel: "low",
    volatilityScore: 3.8,
    isTrapGame: false,
    avoidMatch: false,
    avoidReason: null,
    reasoning:
      "Both teams averaging 115+ points. Fast-paced matchup with no key injuries. Pace differential strongly favors over.",
    keyFactors: ["High scoring form", "No injuries", "Pace matchup"],
    weatherImpact: null,
    sharpMoneySignal: null,
    aiProbability: 65,
    bookmakerProbability: 60,
    valueDetected: false,
    tierRequired: "pro",
  },
  {
    id: "3",
    sport: "soccer",
    league: "Premier League",
    homeTeam: "Arsenal",
    awayTeam: "Chelsea",
    matchDate: new Date().toISOString(),
    prediction: "home_win",
    confidence: 42,
    riskLevel: "high",
    volatilityScore: 8.9,
    isTrapGame: true,
    avoidMatch: true,
    avoidReason: "Derby pressure + 3 Arsenal injuries + suspicious line movement",
    reasoning:
      "High volatility London derby. Three key Arsenal injuries reported. Suspicious line movement detected. Strong recommend to avoid.",
    keyFactors: ["Derby unpredictability", "Arsenal injuries", "Odd line movement"],
    weatherImpact: null,
    sharpMoneySignal: "Unusual reverse line movement",
    aiProbability: 42,
    bookmakerProbability: 48,
    valueDetected: false,
    tierRequired: "free",
  },
  {
    id: "4",
    sport: "mlb",
    league: "MLB",
    homeTeam: "New York Yankees",
    awayTeam: "Boston Red Sox",
    matchDate: new Date().toISOString(),
    prediction: "home_win",
    confidence: 71,
    riskLevel: "low",
    volatilityScore: 4.1,
    isTrapGame: false,
    avoidMatch: false,
    avoidReason: null,
    reasoning:
      "Yankees ace on the mound with 2.8 ERA at home. Red Sox bullpen has been depleted. Lineup matchup heavily favors New York.",
    keyFactors: ["Ace pitcher", "Bullpen advantage", "Home batting stats"],
    weatherImpact: "Clear skies, favorable wind for hitters",
    sharpMoneySignal: null,
    aiProbability: 71,
    bookmakerProbability: 58,
    valueDetected: true,
    tierRequired: "pro",
  },
  {
    id: "5",
    sport: "nba",
    league: "NBA",
    homeTeam: "Golden State Warriors",
    awayTeam: "Los Angeles Lakers",
    matchDate: new Date().toISOString(),
    prediction: "away_win",
    confidence: 58,
    riskLevel: "medium",
    volatilityScore: 5.5,
    isTrapGame: false,
    avoidMatch: false,
    avoidReason: null,
    reasoning:
      "LeBron returning from minor injury with revenge game motivation. Warriors missing key rotation players. Lakers have won 6 straight on the road.",
    keyFactors: ["LeBron return", "Warriors depth issues", "Lakers road form"],
    weatherImpact: null,
    sharpMoneySignal: "Public money on Warriors, sharp on Lakers",
    aiProbability: 58,
    bookmakerProbability: 45,
    valueDetected: true,
    tierRequired: "elite",
  },
  {
    id: "6",
    sport: "soccer",
    league: "La Liga",
    homeTeam: "Real Madrid",
    awayTeam: "Barcelona",
    matchDate: new Date().toISOString(),
    prediction: "draw",
    confidence: 54,
    riskLevel: "medium",
    volatilityScore: 7.2,
    isTrapGame: false,
    avoidMatch: false,
    avoidReason: null,
    reasoning:
      "El Clasico historically volatile with even H2H at Bernabeu. Both teams in similar form. Tactical battle likely to produce low-scoring draw.",
    keyFactors: ["H2H parity", "Tactical setups", "High stakes paralysis"],
    weatherImpact: null,
    sharpMoneySignal: null,
    aiProbability: 54,
    bookmakerProbability: 28,
    valueDetected: true,
    tierRequired: "pro",
  },
];

export const SPORT_FILTERS = [
  { key: "all", label: "All" },
  { key: "nfl", label: "NFL" },
  { key: "nba", label: "NBA" },
  { key: "mlb", label: "MLB" },
  { key: "soccer", label: "Soccer" },
  { key: "value", label: "Value" },
  { key: "avoid", label: "Avoid" },
] as const;

export const SUGGESTED_PROMPTS = [
  "What are the safest NFL picks this week?",
  "Build me a 3-leg accumulator for today",
  "Which games should I avoid today?",
  "How much should I stake on a 75% confidence pick?",
  "Explain closing line value to me",
  "What's the Kelly Criterion formula?",
];
