uploads = []
outputs = []

[[generated]]
id = "llT3EwRdyueK0Gfz2yrdG"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "prediqsai app icon"

[[generated]]
id = "fKdqEBHaoyFJ70KX6b6b1"
uri = "file://artifacts/mobile/assets/images/splash.png"
type = "image"
title = "prediqsai splash clean"
